CREATE DATABASE SAVINNG_PASSBOOK
CREATE TABLE CUSTOMER(
 ID CHAR(6) PRIMARY KEY,
 NAME NVARCHAR(40),--Ten Khach hang
 CUS_ADDRESS NVARCHAR(40),-- Dia chi
 SAVINGBOOK CHAR(6),-- Ma STK
 CMND CHAR(9)
);
GO
CREATE TABLE SAVINGS_ACCOUNT(
ID CHAR(6) PRIMARY KEY,
OPENDATE DATE,-- Ngay mo so
ID_CUS CHAR(6),-- Ma khach hang
ACCOUNT_BALANCE MONEY,-- So du
TYPE_ACCOUNT CHAR(4)--Ma loai TK
);
GO
CREATE TABLE TYPE_ACCOUNT (
ID CHAR(6) PRIMARY KEY,
TYPENAME VARCHAR(40),
INTEREST_RATE FLOAT,-- Lai suat
LIMIT_TIME INT-- So Thang thoi han lai suat
);
GO
CREATE TABLE COLLECTBILL (
ID CHAR(6) PRIMARY KEY,
ID_PASSBOOK CHAR(6),
COLLECT_MONEY MONEY,
EXDATE DATE,--Ngay goi
);
GO
CREATE TABLE WITHDRAWBILL (
ID CHAR(6) PRIMARY KEY,
ID_PASSBOOK CHAR(6),
EXDATE DATE,
DRAW_MONEY MONEY-- Ngay rut
);
GO
ALTER TABLE SAVINGS_ACCOUNT ALTER COLUMN TYPE_ACCOUNT CHAR(6) 
ALTER TABLE  SAVINGS_ACCOUNT ADD CONSTRAINT FK_SAVINGSACCOUNT_IDCUS FOREIGN KEY (ID_CUS) REFERENCES CUSTOMER (ID);
ALTER TABLE  SAVINGS_ACCOUNT ADD CONSTRAINT FK_SAVINGSACCOUNT_TYPEACCUONT FOREIGN KEY (TYPE_ACCOUNT) REFERENCES TYPE_ACCOUNT (ID);
ALTER TABLE  COLLECTBILL ADD CONSTRAINT FK_COLLECTBILL_IDPASSBOOK FOREIGN KEY (ID_PASSBOOK) REFERENCES SAVINGS_ACCOUNT (ID);
ALTER TABLE  WITHDRAWBILL ADD CONSTRAINT FK_WITHDRAWBILL_IDPASSBOOK FOREIGN KEY (ID_PASSBOOK) REFERENCES SAVINGS_ACCOUNT (ID);
GO
 CREATE TABLE PARAMETER 
 (
 AT_LEAST_MONEY_FST MONEY,--So tien goi ban dau toi thieu
 AT_LEAST_EXTRA_MONEY MONEY-- So tien goi toi thieu
 )
 GO
